// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGR6etkFycRiletFK2kZmj7amnsfrLdlQ',
    appId: '1:427011389675:web:f4393a2e7d0ab4848026ae',
    messagingSenderId: '427011389675',
    projectId: 'my-music-list-prototype',
    authDomain: 'my-music-list-prototype.firebaseapp.com',
    storageBucket: 'my-music-list-prototype.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAmz1UYVT0gQ1EcGxW6wyJBLI6ltQZBqQ',
    appId: '1:427011389675:android:72a1130bf1f597a88026ae',
    messagingSenderId: '427011389675',
    projectId: 'my-music-list-prototype',
    storageBucket: 'my-music-list-prototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfzZo9Et3Y842Jf56kZy_yS1GU5ITWUUI',
    appId: '1:427011389675:ios:1617e3348f8cfd968026ae',
    messagingSenderId: '427011389675',
    projectId: 'my-music-list-prototype',
    storageBucket: 'my-music-list-prototype.appspot.com',
    iosClientId: '427011389675-0oelbridg8s03op3art10f8igabeo0t9.apps.googleusercontent.com',
    iosBundleId: 'com.yummy.mymusiclist.myMusicList',
  );
}
